#!/bin/bash

pcount=$#
if((pcount==0)); then
echo no args;
exit;
fi
p1=$1
fname=`basename $p1`
echo fname=$fname
pdir=`cd -P $(dirname $p1); pwd`
echo pdir=$pdir
user=`whoami`
# change hadoop workers to youself
workfile=/home/servers/hadoop-3.1.4/etc/hadoop/workers
works=`cat $workfile`
cat $workfile | xargs -i ssh {} "mkdir -p $pdir"
for host in $works
do
 echo ------------------- $host --------------
 rsync -rvl $pdir/$fname $user@$host:$pdir
 echo ----------------- rsync done --------------
done
